before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql -c 'create database blocitoff_test;' -U postgres
  - rails db:migrate RAILS_ENV=test
rvm:
  - 2.3.3
sudo: false
