default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default


test:
  <<: *default
  database: blocitoff_test

production:
  <<: *default
